select
    AMBS_CUST_NBR,
    AMBS_ACCT,
    AMBS_DATE_OPENED,
    AMBS_DATE_LAST_MAINT,
    AIRFLOW_DAG_TIME,
    AMBS_CRLIM as CREDIT_LIMIT_AMOUNT,
    AMBS_CASH_CRLIM as CASH_LIMIT_AMOUNT,
    AMBS_DATE_CLOSED,
    AMBS_CURR_CODE
from DATAOPS_HUB_SHARE_VISION_NONPROD.RAW.ACCOUNT_BASE_SEGMENT
where AMBS_CUST_NBR = '<CUSTOMER_ID>'
  and AMBS_ACCT = '0005039468177827600'
order by
    AMBS_DATE_LAST_MAINT,
    AIRFLOW_DAG_TIME;